# Generated by Django 6.0.2 on 2026-02-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('categoria', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], max_length=20)),
                ('tipo', models.CharField(choices=[('vestido', 'Vestido'), ('blusa', 'Blusa'), ('falda', 'Falda'), ('chaleco', 'Chaleco'), ('pantalon', 'Pantalón'), ('camisa', 'Camisa'), ('saco', 'Saco'), ('sueter', 'Suéter'), ('traje', 'Traje')], max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_corta', models.TextField(max_length=300)),
                ('descripcion_larga', models.TextField()),
                ('material', models.CharField(default='95% Poliéster, 5% Elastano', max_length=200)),
                ('largo', models.CharField(blank=True, max_length=100)),
                ('cuidado', models.CharField(default='Lavado a mano o seco', max_length=200)),
                ('disponible', models.BooleanField(default=True)),
                ('destacada', models.BooleanField(default=False, help_text='Marcar si esta prenda debe aparecer en la página de inicio', verbose_name='Prenda Destacada')),
                ('tallas_disponibles', models.CharField(default='XS,S,M,L,XL', help_text='Separar con comas', max_length=50)),
                ('guia_tallas', models.JSONField(blank=True, default=dict, help_text='Guía de tallas específica para esta prenda')),
                ('colores_disponibles', models.CharField(blank=True, default='', help_text='Formato: Negro:#1a1a1a,Blanco:#ffffff', max_length=200)),
                ('imagen_principal', models.ImageField(max_length=500, upload_to='')),
                ('imagen_2', models.ImageField(blank=True, max_length=500, upload_to='')),
                ('imagen_3', models.ImageField(blank=True, max_length=500, upload_to='')),
                ('imagen_4', models.ImageField(blank=True, max_length=500, upload_to='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prenda',
                'verbose_name_plural': 'Prendas',
                'ordering': ['-destacada', '-fecha_creacion'],
            },
        ),
    ]
