# Generated by Django 5.2.6 on 2026-01-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='guia_tallas',
            field=models.JSONField(blank=True, default=dict, help_text='Guía de tallas específica para esta prenda'),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='imagen_2',
            field=models.ImageField(blank=True, max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='imagen_3',
            field=models.ImageField(blank=True, max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='imagen_4',
            field=models.ImageField(blank=True, max_length=500, upload_to=''),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='imagen_principal',
            field=models.ImageField(max_length=500, upload_to=''),
        ),
    ]
