# Generated by Django 6.0.2 on 2026-02-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matys', '0001_initial'),
    ]

    operations = [
    ]
