# Generated by Django 6.0.3 on 2026-05-19 01:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matys', '0003_imagenprenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenprenda',
            name='imagen',
            field=cloudinary.models.CloudinaryField(help_text='Subí la foto de la prenda. Formatos aceptados: JPG, PNG, WEBP.', max_length=255, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='imagenprenda',
            name='orden',
            field=models.IntegerField(default=0, help_text='Posición en la galería. La imagen con orden 0 es la foto principal que aparece en el catálogo.'),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='TipoPrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('categoria', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tipo de prenda',
                'verbose_name_plural': 'Tipos de prenda',
                'ordering': ['categoria', 'orden', 'nombre'],
                'unique_together': {('slug', 'categoria')},
            },
        ),
    ]
