# Generated by Django 6.0.3 on 2026-05-25 18:16

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matys', '0003_imagenprenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenprenda',
            name='imagen',
            field=cloudinary.models.CloudinaryField(help_text='Subí la foto de la prenda. Formatos aceptados: JPG, PNG, WEBP.', max_length=255, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='imagenprenda',
            name='orden',
            field=models.IntegerField(default=0, help_text='Posición en la galería. La imagen con orden 0 es la foto principal que aparece en el catálogo.'),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='categoria',
            field=models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino'), ('infantil', 'Infantil')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='tipo',
            field=models.CharField(choices=[('vestido_gala', 'Vestido de gala'), ('vestido_casual', 'Vestido casual'), ('vestido_semiformal', 'Vestido semiformal'), ('vestido_novia', 'Vestido de novia'), ('vestido_quince', 'Vestido de quinceañera'), ('vestido_alusivo', 'Vestido alusivo'), ('vestido_playero', 'Vestido playero'), ('blusa', 'Blusa'), ('falda', 'Falda'), ('chaleco', 'Chaleco'), ('pantalon', 'Pantalón'), ('traje', 'Traje'), ('traje_alusivo', 'Traje alusivo'), ('sueter', 'Suéter'), ('camisa', 'Camisa'), ('saco', 'Saco'), ('smoking', 'Smoking completo'), ('dos_piezas', 'Traje 2 piezas'), ('infantil_general', 'General infantil')], max_length=50),
        ),
    ]
