# Generated by Django 6.0.3 on 2026-09-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matys', '0009_siteconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(default='llama-3.1-8b-instant', max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Éxito'), ('error', 'Error')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Uso de IA',
                'verbose_name_plural': 'Uso de IA',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='matys_aiusa_timesta_ab0fab_idx')],
            },
        ),
    ]
