# Generated by Django 6.0.3 on 2026-09-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matys', '0010_aiusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusage',
            name='model',
            field=models.CharField(default='openai/gpt-oss-20b', max_length=100),
        ),
    ]
