# Generated by Django 6.0.3 on 2026-09-14 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matys', '0011_update_aiusage_default_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
